---
title: "Polar/Pizza_Tutorial"
output: html_document
---

# Package
```{r}
library(tidyverse)
library(ggplot2)
library(devtools)
#devtools::install_github("JaseZiv/worldfootballR")
library(worldfootballR)
```

# Basketball
```{r}
index <- 1:12
stat <- c("Points Per Shot", "2-Point %", "3-Point %", "Free Throw Rate", "Usage %", "Assist %", "Ball Security",
          "Off. Rebounding %", "Block %", "Steal %", "Defensive BPM", "Def. Rebounding %")
value <- c("10", "20", "30", "40", "50", "60", "40", "50", "70", "80", "90", "100")

data <- as.data.frame(cbind(index, stat, value))

data <- data %>% 
  mutate(type = case_when(
    index %in% 1:4 ~ "Scoring",
    index %in% 5:8 ~ "Possession",
    index %in% 9:12 ~ "Defending"
  ))

data$index <- as.numeric(data$index)
data$value <- as.numeric(data$value)

data$type <- factor(data$type, levels = c("Scoring", "Possession", "Defending"))

## ---- Rotate axis text in plot

# angle of axis text
temp <- (360/(length(data$index))/2)                             
#find the difference in angle between to labels and divide by two.
myAng <- seq(-temp, -360+temp, length.out = length(data$index))  
#get the angle for every label
ang<-ifelse(myAng < -90, myAng+180, myAng)                                    
#rotate label by 180 in some places for readability
ang<-ifelse(ang < -90, ang+180, ang)
```

```{r}
color1 <- "#552583"
color2 <- "grey"
color3 <- "#FDB927"

ggplot(data = data, aes(x = reorder(stat, index), y = value, label= value, fill = type)) +
  # add the bar/pizza slices that are colored
  geom_bar(data = data, width = 1,
           color = "oldlace",
           stat = "identity") +
  # wrap bar chart as around polar center
  coord_polar() +    
  # add the background behind each bar (alpha at .5 for slight transparency so the bars standout)
  geom_bar(aes(y=100, fill=type), stat="identity", width=1, alpha=0.5) +
  # add & customize line that border whole pizza
  geom_hline(yintercept = seq(0, 100, by = 100),
             color = "oldlace",
             size = 1) +
  # add & customize lines between each pizza slice
  geom_vline(xintercept = seq(.5, 12, by = 1),
             color = "oldlace",
             size = .5) +
  # add percentile labels (labels are fill by bar colors) - option 1
    #geom_label(aes(label=value, fill=type), color = "white", size=2.5, fontface="bold", family = "Comic Sans MS", show.legend = FALSE) +
  # add percentile labels (labels are choice of fill and color) - option 2
  geom_label(color = "gray20", fill = "oldlace", size=2.5, fontface="bold", family = "Comic Sans MS", show.legend = FALSE) +
  # manually set the colors of bars (3 here for each group of stats (scoring, possession, defending))
  scale_fill_manual(values=c(color1, color2, color3)) +
  # theme manipulation to customize plot (play around with these!)
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.background = element_rect(fill = "oldlace", color="oldlace"),
        legend.title = element_blank(),
        legend.text = element_text(colour = "gray20", family = "Comic Sans MS", face = "bold"),
        legend.key.size = unit(.5, "cm"),
        legend.box.spacing = unit(0, "mm"),
        plot.title = element_text(hjust = .5, colour = "gray20", face = "bold", size = 16, family = "Comic Sans MS"),
        plot.subtitle = element_text(hjust = .5, colour = "gray20", size = 8, family = "Comic Sans MS"),
        plot.background = element_rect(fill = "oldlace", color="oldlace"),
        panel.background = element_rect(fill = "oldlace", color="oldlace"),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold", size = 6.8, colour = "gray20"),
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold", size = 7, family = "Comic Sans MS", angle = ang)) +
  # add title and subtitle
  labs(title = "LeBron James Percentile Rankings",
       subtitle = "@DSamangy // via: basketball-reference", x = NULL, y = NULL)

# save plot
#ggsave("lebron_polar.png", height = 6, width = 6, dpi = "retina")
```

# Soccer
```{r}
df <- fb_player_scouting_report("https://fbref.com/en/players/9674002f/Mason-Mount", pos_versus = "primary")

player_df <- df[c(9,24,10,73,47,125,131,119,97,108,107,146),]

player_df$index <- 1:12

player_df <- player_df %>% 
  mutate(type = case_when(
    index %in% 1:4 ~ "Attacking",
    index %in% 5:8 ~ "Possession",
    index %in% 9:12 ~ "Defending"
  ))

player_df$type <- factor(player_df$type, levels = c("Attacking", "Possession", "Defending"))

## ---- Rotate axis text in plot

# angle of axis text
temp <- (360/(length(player_df$index))/2)                             
#find the difference in angle between to labels and divide by two.
myAng <- seq(-temp, -360+temp, length.out = length(player_df$index))  
#get the angle for every label
ang<-ifelse(myAng < -90, myAng+180, myAng)                                    
#rotate label by 180 in some places for readability
ang<-ifelse(ang < -90, ang+180, ang)
```

```{r}
color1 <- "#034694"
color2 <- "grey"
color3 <- "gold"

ggplot(data = player_df, aes(x = reorder(Statistic, index), y = Percentile, label= Percentile, fill = type)) +
  # add the bar/pizza slices that are colored
  geom_bar(data = player_df, width = 1,
           color = "oldlace",
           stat = "identity") +
  # wrap bar chart as around polar center
  coord_polar() +    
  # add the background behind each bar (alpha at .5 for slight transparency so the bars standout)
  geom_bar(aes(y=100, fill=type), stat="identity", width=1, alpha=0.5) +
  # add & customize line that border whole pizza
  geom_hline(yintercept = seq(0, 100, by = 100),
             color = "oldlace",
             size = 1) +
  # add & customize lines between each pizza slice
  geom_vline(xintercept = seq(.5, 12, by = 1),
             color = "oldlace",
             size = .5) +
  # add percentile labels (labels are fill by bar colors) - option 1
    #geom_label(aes(label=value, fill=type), color = "white", size=2.5, fontface="bold", family = "Comic Sans MS", show.legend = FALSE) +
  # add percentile labels (labels are choice of fill and color) - option 2
  geom_label(color = "gray20", fill = "oldlace", size=2.5, fontface="bold", family = "Comic Sans MS", show.legend = FALSE) +
  # manually set the colors of bars (3 here for each group of stats (scoring, possession, defending))
  scale_fill_manual(values=c(color1, color2, color3)) +
  # theme manipulation to customize plot (play around with these!)
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.background = element_rect(fill = "oldlace", color="oldlace"),
        legend.title = element_blank(),
        legend.text = element_text(colour = "gray20", family = "Comic Sans MS", face = "bold"),
        legend.key.size = unit(.5, "cm"),
        legend.box.spacing = unit(0, "mm"),
        plot.title = element_text(hjust = .5, colour = "gray20", face = "bold", size = 16, family = "Comic Sans MS"),
        plot.subtitle = element_text(hjust = .5, colour = "gray20", size = 8, family = "Comic Sans MS"),
        plot.background = element_rect(fill = "oldlace", color="oldlace"),
        panel.background = element_rect(fill = "oldlace", color="oldlace"),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold", size = 6.8, colour = "gray20"),
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold", size = 7, family = "Comic Sans MS", angle = ang)) +
  # add title and subtitle
  labs(title = "Mason Mount Scouting Report",
       subtitle = "@DSamangy // Last 365 Days // via: worldfootballR", x = NULL, y = NULL)

# save plot
#ggsave("mount_polar.png", height = 6, width = 6, dpi = "retina")
```


